# Generated by Django 5.2 on 2025-06-17 08:45

import clientPanel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientPanel', '0003_sync_user_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocument',
            name='document',
            field=models.FileField(upload_to=clientPanel.models.UserDocument.user_document_path),
        ),
    ]
