# Generated by Django 5.2 on 2025-09-17 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientPanel', '0005_add_branch_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PAMAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name for the PAMM account', max_length=200)),
                ('strategy', models.CharField(blank=True, help_text='Trading strategy description', max_length=200, null=True)),
                ('min_investment', models.DecimalField(decimal_places=2, default=0, help_text='Minimum investment amount', max_digits=14)),
                ('profit_share', models.DecimalField(decimal_places=2, default=0, help_text='Manager profit share in percent', max_digits=5)),
                ('leverage', models.IntegerField(default=100, help_text='Leverage for this PAMM account')),
                ('mt5_login', models.CharField(blank=True, help_text='MT5 account login ID', max_length=64, null=True)),
                ('master_password', models.CharField(blank=True, help_text='Master password for trading', max_length=128, null=True)),
                ('investor_password', models.CharField(blank=True, help_text='Investor password for viewing', max_length=128, null=True)),
                ('enabled', models.BooleanField(default=True, help_text='Whether this PAMM account is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pam_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PAMM Account',
                'verbose_name_plural': 'PAMM Accounts',
            },
        ),
        migrations.CreateModel(
            name='PAMProfitHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('profit_amount', models.DecimalField(decimal_places=2, help_text='Profit amount distributed', max_digits=16)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pam_profit_history', to=settings.AUTH_USER_MODEL)),
                ('pam_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_history', to='clientPanel.pamaccount')),
            ],
            options={
                'verbose_name': 'PAMM Profit History',
                'verbose_name_plural': 'PAMM Profit History',
            },
        ),
        migrations.CreateModel(
            name='PAMInvestment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Investment amount', max_digits=16)),
                ('profit_share', models.DecimalField(decimal_places=2, default=0, help_text='Investor share in percent', max_digits=5)),
                ('mt5_allocation_id', models.CharField(blank=True, help_text='MT5 allocation identifier', max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pam_investments', to=settings.AUTH_USER_MODEL)),
                ('pam_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='clientPanel.pamaccount')),
            ],
            options={
                'verbose_name': 'PAMM Investment',
                'verbose_name_plural': 'PAMM Investments',
                'unique_together': {('investor', 'pam_account')},
            },
        ),
    ]
