# Generated by Django 5.2 on 2025-11-03 14:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientPanel', '0006_pamaccount_pamprofithistory_paminvestment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='mime_type',
            field=models.CharField(blank=True, help_text='MIME type of the uploaded document', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='user_email',
            field=models.EmailField(db_index=True, default='temp@example.com', help_text='User email for faster document retrieval', max_length=254),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when document was verified', null=True),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='document_type',
            field=models.CharField(choices=[('identity', 'Identity Document'), ('residence', 'Proof of Residence')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='userdocument',
            index=models.Index(fields=['user_email', 'document_type'], name='userdoc_email_type_idx'),
        ),
        migrations.AddIndex(
            model_name='userdocument',
            index=models.Index(fields=['user_email', 'status'], name='userdoc_email_status_idx'),
        ),
        migrations.AddIndex(
            model_name='userdocument',
            index=models.Index(fields=['document_type', 'status'], name='userdoc_type_status_idx'),
        ),
    ]
